### ISSUE TITLE
Calculate all conditional independencies of an ADMG

### ISSUE THREAD

**Issue by djinnome** [y0-causal-inference/y0#24]
Given:  ADMG
Output: pair of nodes, X,Y that are independent given a set Z of observation nodes.

There is already a data structure that represents a conditional independency in https://github.com/y0-causal-inference/y0/blob/main/src/y0/struct.py. Further, the list of conditional independencies for several example graphs from Causal Fusion can be imported from https://github.com/y0-causal-inference/y0/blob/main/src/y0/examples.py Both of these allow for easy test-driven development.

**Comment by JosephCottam** [comment]
Conditional independencies are in fact calculating on ADMG!

However, one of the tests is incorrect (refers to a variable that is not in the graph) and thus fails.   This should be fixed before this issue is closed.

Decisions to be made:
1)  DSeparationJudgement and ConditionalIndependency overlap a lot conceptually and in implementation.  Should they be merged?
2) As constructed, a ConditionalIndependency object can be constructed that is actually not one in the graph it is drawn from.  Should we enforce validation in create?
3) ConditionalIndependnecy objects current hold DSL Variables in them, but the ADMG graph nodes do not necessarily. Coupling it requires wrapping/unwrapping variables referred to at various times (increasing code complexity and mental load).  What do we gain by coupling ConditionalIndependency to the DSL explicitly?   The most apparently alternative would be to have the ConditionalIndependency use values that are equal (`==`) to the elements of the ADMG pulled from.

**Comment by cthoyt** [comment]
1. Yes!
2. No, I think we can assume that our software will make all instances of this (except in the case of unit test curation, which I did by hand while reading the results from the output of `causaleffect`)
3. Not a lot is to be gained when it's only the variable names. I might have done this in the beginning because I thought we might have to use some of the features of the DSL, but this seems to not be the case. We can use python's `@property` to make convenient builders for variables based on the names in the ConditionalIndependency class for any downstream code that might want to use it that way
